# Introduction to Numpy

prepared by : Ali Kazempour - autumn 2024

Contact me : https://t.me/A_Kazempour83


In [145]:
import numpy as np 

In [146]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [147]:
arr1[0],arr1[4]

(1, 5)

In [148]:
arr1[1:3] , arr1[0:5:2]

(array([2, 3]), array([1, 3, 5]))

In [149]:
arr2 = np.array([[10,20,30,40],
                [50,60,70,80]])
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [150]:
arr2[1,0] , arr2[0,3] , arr2[1,3]

(50, 40, 80)

In [151]:
arr2[:,2:] , arr2[1,:2]

(array([[30, 40],
        [70, 80]]),
 array([50, 60]))

In [152]:
# creates an identity matrix
I = np.eye(3) 
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [153]:
#  creates an array filled with zeros
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [154]:
# creates an array filled with ones
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [155]:
# creates an array filled with a specified value
np.full((5,6), fill_value = 5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [156]:
# creates an array with evenly spaced values
np.arange(0,10,3)

array([0, 3, 6, 9])

In [157]:
# creates an array with specified number of evenly spaced values between a start and end
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [158]:
# creates an array with normally distributed values
np.random.normal(0, 1,(5,4))

array([[ 1.9536168 ,  0.03770903,  0.95579331,  1.28159056],
       [ 1.08510039,  0.82044714, -1.05396646, -3.28946964],
       [-0.17017254, -1.18342565,  0.84440661, -0.83487097],
       [-1.36369784, -1.42097065,  0.79697707, -0.52281087],
       [ 0.09476648,  1.41087569,  0.87536647, -0.85539667]])

In [159]:
# creates an array with random values
np.random.random((5,4))

array([[0.24263847, 0.27861789, 0.61465088, 0.62117694],
       [0.40727879, 0.47730416, 0.37768375, 0.26923225],
       [0.27820795, 0.80920894, 0.48600904, 0.23606404],
       [0.72925979, 0.18915009, 0.78205871, 0.41527884],
       [0.96112328, 0.84949926, 0.85347232, 0.57231628]])

In [160]:
# creates an array with random integers
np.random.randint(1,10,(5,4))

array([[4, 5, 2, 9],
       [1, 7, 3, 7],
       [2, 5, 7, 7],
       [8, 7, 6, 1],
       [8, 6, 5, 4]])

In [161]:
# returns the shape of the array
arr1.shape , arr2.shape 

((5,), (2, 4))

In [162]:
# returns the number of elements in the array
len(arr1) , len(arr2) 

(5, 2)

In [163]:
# returns the number of dimensions
arr1.ndim , arr2.ndim 

(1, 2)

In [164]:
# returns the data type
arr1.dtype , arr2.dtype 

(dtype('int32'), dtype('int32'))

In [165]:
# returns the total number of elements
arr1.size , arr2.size 

(5, 8)

In [166]:
m = np.array([[12,15,16],
            [17,18,19],
            [20,21,22]])

m

array([[12, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [167]:
# adds two arrays
m + m  

array([[24, 30, 32],
       [34, 36, 38],
       [40, 42, 44]])

In [168]:
# multiplies an array with a scalar
m * 3 

array([[36, 45, 48],
       [51, 54, 57],
       [60, 63, 66]])

In [169]:
# subtracts two arrays
m - m 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [170]:
# to raise an array to a power
m ** 3 

array([[ 1728,  3375,  4096],
       [ 4913,  5832,  6859],
       [ 8000,  9261, 10648]], dtype=int32)

In [171]:
# element wise multiplication
m * m  

array([[144, 225, 256],
       [289, 324, 361],
       [400, 441, 484]])

In [172]:
# transpose
m.T 

array([[12, 17, 20],
       [15, 18, 21],
       [16, 19, 22]])

In [173]:
n = np.array([[1,2],
              [3,4]])
m = np.array([[5,6],
              [7,8]])
n,m

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [174]:
# dot product
np.dot(n,m) 

array([[19, 22],
       [43, 50]])

In [175]:
# another way to do dot product
n.dot(m)

array([[19, 22],
       [43, 50]])

In [176]:
# another way to do dot product 
n @ m # the most efficient way

array([[19, 22],
       [43, 50]])

In [177]:
# copies an array
m1 = m.copy()
m1[0,0] = 100
m1[0,1] = 200
m1

array([[100, 200],
       [  7,   8]])

In [178]:
X = np.random.randint(1,10,(5,4))
X

array([[8, 5, 2, 9],
       [8, 6, 6, 5],
       [7, 5, 2, 2],
       [3, 1, 3, 5],
       [4, 4, 5, 5]])

In [179]:
# returns the mean of each column
X.mean(axis = 0) 

array([6. , 4.2, 3.6, 5.2])

In [180]:
# returns the mean of each row
X.mean(axis = 1) 

array([6.  , 6.25, 4.  , 3.  , 4.5 ])

In [181]:
# returns the variance of each column
X.var(axis = 0) 

array([4.4 , 2.96, 2.64, 4.96])

In [182]:
# returns the sum of each row
X.sum(axis = 1) 

array([24, 25, 16, 12, 18])

In [183]:
# min of each column
X.min(axis = 0) 

array([3, 1, 2, 2])

In [184]:
# max of each row
X.max(axis = 0) 

array([8, 6, 6, 9])

In [185]:
X.shape

(5, 4)

In [186]:
# reshapes the array
X.reshape(10,2) 

array([[8, 5],
       [2, 9],
       [8, 6],
       [6, 5],
       [7, 5],
       [2, 2],
       [3, 1],
       [3, 5],
       [4, 4],
       [5, 5]])

In [187]:
A = np.random.randint(1,10,(3,3))
A

array([[8, 2, 3],
       [7, 6, 7],
       [6, 2, 5]])

In [188]:
# inverts the matrix
A_inv = np.linalg.inv(A) 
A_inv

array([[ 0.21052632, -0.05263158, -0.05263158],
       [ 0.09210526,  0.28947368, -0.46052632],
       [-0.28947368, -0.05263158,  0.44736842]])