# Introduction to Numpy

## prepared by : Ali Kazempour - autumn 2024

## Contact me : https://t.me/A_Kazempour83


In [189]:
import numpy as np 

In [190]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [191]:
arr1[0],arr1[4]

(1, 5)

In [192]:
arr1[1:3] , arr1[0:5:2]

(array([2, 3]), array([1, 3, 5]))

In [193]:
arr2 = np.array([[10,20,30,40],
                [50,60,70,80]])
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [194]:
arr2[1,0] , arr2[0,3] , arr2[1,3]

(50, 40, 80)

In [195]:
arr2[:,2:] , arr2[1,:2]

(array([[30, 40],
        [70, 80]]),
 array([50, 60]))

In [196]:
# creates an identity matrix
I = np.eye(3) 
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [197]:
#  creates an array filled with zeros
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [198]:
# creates an array filled with ones
np.ones((4,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [199]:
# creates an array filled with a specified value
np.full((5,6), fill_value = 5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [200]:
# creates an array with evenly spaced values
np.arange(0,10,3)

array([0, 3, 6, 9])

In [201]:
# creates an array with specified number of evenly spaced values between a start and end
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [202]:
# creates an array with normally distributed values
np.random.normal(0, 1,(5,4))

array([[ 0.87820886, -0.43369124,  1.41533425,  0.42971887],
       [ 0.59751475,  0.66510268,  0.95639808, -0.93261511],
       [ 0.8401853 , -1.04296867,  0.26700083,  1.60854309],
       [ 0.10553492, -0.91967027, -0.308838  ,  2.3625253 ],
       [-0.39635133, -0.49906264, -0.42261503, -0.53850548]])

In [203]:
# creates an array with random values
np.random.random((5,4))

array([[0.168318  , 0.87719924, 0.2369107 , 0.88226782],
       [0.2557918 , 0.22159267, 0.44265083, 0.61938708],
       [0.66344997, 0.25055564, 0.65702427, 0.40715159],
       [0.3263473 , 0.93053693, 0.63552681, 0.13483502],
       [0.17110475, 0.12532478, 0.75926475, 0.59009637]])

In [204]:
# creates an array with random integers
np.random.randint(1,10,(5,4))

array([[5, 8, 5, 4],
       [9, 5, 4, 3],
       [9, 8, 2, 9],
       [2, 6, 4, 8],
       [4, 7, 8, 9]])

In [205]:
# returns the shape of the array
arr1.shape , arr2.shape 

((5,), (2, 4))

In [206]:
# returns the number of elements in the array
len(arr1) , len(arr2) 

(5, 2)

In [207]:
# returns the number of dimensions
arr1.ndim , arr2.ndim 

(1, 2)

In [208]:
# returns the data type
arr1.dtype , arr2.dtype 

(dtype('int32'), dtype('int32'))

In [209]:
# returns the total number of elements
arr1.size , arr2.size 

(5, 8)

In [210]:
m = np.array([[12,15,16],
            [17,18,19],
            [20,21,22]])

m

array([[12, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [211]:
# adds two arrays
m + m  

array([[24, 30, 32],
       [34, 36, 38],
       [40, 42, 44]])

In [212]:
# multiplies an array with a scalar
m * 3 

array([[36, 45, 48],
       [51, 54, 57],
       [60, 63, 66]])

In [213]:
# subtracts two arrays
m - m 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [214]:
# to raise an array to a power
m ** 3 

array([[ 1728,  3375,  4096],
       [ 4913,  5832,  6859],
       [ 8000,  9261, 10648]], dtype=int32)

In [215]:
# element wise multiplication
m * m  

array([[144, 225, 256],
       [289, 324, 361],
       [400, 441, 484]])

In [216]:
# transpose
m.T 

array([[12, 17, 20],
       [15, 18, 21],
       [16, 19, 22]])

In [217]:
n = np.array([[1,2],
              [3,4]])
m = np.array([[5,6],
              [7,8]])
n,m

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [218]:
# dot product
np.dot(n,m) 

array([[19, 22],
       [43, 50]])

In [219]:
# another way to do dot product
n.dot(m)

array([[19, 22],
       [43, 50]])

In [220]:
# another way to do dot product 
n @ m # the most efficient way

array([[19, 22],
       [43, 50]])

In [221]:
# copies an array
m1 = m.copy()
m1[0,0] = 100
m1[0,1] = 200
m1

array([[100, 200],
       [  7,   8]])

In [222]:
X = np.random.randint(1,10,(5,4))
X

array([[3, 6, 4, 8],
       [4, 8, 5, 4],
       [2, 6, 1, 8],
       [8, 8, 6, 7],
       [1, 7, 1, 9]])

In [223]:
# returns the mean of each column
X.mean(axis = 0) 

array([3.6, 7. , 3.4, 7.2])

In [224]:
# returns the mean of each row
X.mean(axis = 1) 

array([5.25, 5.25, 4.25, 7.25, 4.5 ])

In [225]:
# returns the variance of each column
X.var(axis = 0) 

array([5.84, 0.8 , 4.24, 2.96])

In [226]:
# returns the sum of each row
X.sum(axis = 1) 

array([21, 21, 17, 29, 18])

In [227]:
# min of each column
X.min(axis = 0) 

array([1, 6, 1, 4])

In [228]:
# max of each row
X.max(axis = 0) 

array([8, 8, 6, 9])

In [229]:
X.shape

(5, 4)

In [230]:
# reshapes the array
X.reshape(10,2) 

array([[3, 6],
       [4, 8],
       [4, 8],
       [5, 4],
       [2, 6],
       [1, 8],
       [8, 8],
       [6, 7],
       [1, 7],
       [1, 9]])

In [231]:
A = np.random.randint(1,10,(3,3))
A

array([[8, 2, 2],
       [3, 2, 3],
       [5, 2, 1]])

In [232]:
# inverts the matrix
A_inv = np.linalg.inv(A) 
A_inv

array([[ 0.25 , -0.125, -0.125],
       [-0.75 ,  0.125,  1.125],
       [ 0.25 ,  0.375, -0.625]])